#### This practice covers the train test split , feature scaling and column transformations applied using the inbuilt scikit learn framework as well as custom functions using the function transformer

In [21]:
import pandas as pd

df= pd.read_csv("../datasets/employees.csv")
df.head()

   Age  Salary Department  Education     City  Experience Promoted
0   23   45000         IT  Bachelors  Nairobi           1       No
1   31   72000    Finance    Masters  Mombasa           5      Yes
2   28   58000         IT  Bachelors  Nairobi           3       No
3   42   95000         HR        PhD   Kisumu          12      Yes
4   35   68000  Marketing    Masters  Nairobi           7      Yes

In [22]:
y=df["Promoted"]
y

0      No
1     Yes
2      No
3     Yes
4     Yes
5      No
6      No
7     Yes
8      No
9     Yes
10     No
11    Yes
12     No
13    Yes
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20     No
21    Yes
22    Yes
23     No
24    Yes
25     No
26    Yes
27    Yes
28     No
29    Yes
30     No
31    Yes
32    Yes
33     No
34    Yes
35     No
36    Yes
37     No
38    Yes
39    Yes
40     No
41    Yes
42     No
43    Yes
44    Yes
45     No
46    Yes
47     No
48    Yes
49     No
Name: Promoted, dtype: str

In [23]:
x=df.drop(columns="Promoted")
x

    Age  Salary Department  Education     City  Experience
0    23   45000         IT  Bachelors  Nairobi           1
1    31   72000    Finance    Masters  Mombasa           5
2    28   58000         IT  Bachelors  Nairobi           3
3    42   95000         HR        PhD   Kisumu          12
4    35   68000  Marketing    Masters  Nairobi           7
5    24   42000    Finance  Bachelors  Eldoret           1
6    29   61000         IT    Masters   Nakuru           4
7    38   83000         HR  Bachelors  Mombasa           9
8    26   50000  Marketing  Bachelors   Kisumu           2
9    45  110000    Finance        PhD  Nairobi          18
10   27   54000         IT  Bachelors  Eldoret           3
11   33   76000    Finance    Masters  Nairobi           6
12   30   63000  Marketing  Bachelors  Mombasa           5
13   41   90000         HR    Masters   Kisumu          11
14   36   71000         IT    Masters   Nakuru           8
15   25   47000    Finance  Bachelors  Nairobi           2
16   32   67000  Marketing    Masters  Eldoret           6
17   39   85000         HR  Bachelors  Nairobi          10
18   28   56000         IT  Bachelors  Mombasa           3
19   44  102000    Finance        PhD   Kisumu          16
20   22   40000  Marketing  Bachelors   Nakuru           1
21   34   70000         IT    Masters  Nairobi           7
22   37   79000    Finance    Masters  Mombasa           9
23   29   59000         HR  Bachelors  Eldoret           4
24   43   98000         IT        PhD  Nairobi          15
25   26   51000  Marketing  Bachelors   Nakuru           2
26   31   65000         HR    Masters   Kisumu           6
27   35   74000    Finance  Bachelors  Nairobi           8
28   27   53000         IT  Bachelors  Mombasa           3
29   40   88000  Marketing    Masters  Eldoret          12
30   24   43000         HR  Bachelors  Nairobi           1
31   33   69000         IT    Masters   Kisumu           7
32   38   82000    Finance    Masters   Nakuru          10
33   30   60000  Marketing  Bachelors  Nairobi           5
34   46  115000         HR        PhD  Mombasa          19
35   25   48000         IT  Bachelors  Eldoret           2
36   36   77000    Finance    Masters  Nairobi           9
37   29   57000  Marketing  Bachelors   Kisumu           4
38   42   93000         IT        PhD   Nakuru          14
39   32   66000         HR    Masters  Mombasa           6
40   23   41000    Finance  Bachelors  Nairobi           1
41   37   80000  Marketing    Masters  Eldoret          10
42   28   55000         IT  Bachelors   Kisumu           3
43   34   73000         HR    Masters  Nairobi           8
44   41   91000    Finance        PhD  Mombasa          13
45   26   49000  Marketing  Bachelors   Nakuru           2
46   39   86000         IT    Masters  Nairobi          11
47   30   62000         HR  Bachelors  Eldoret           5
48   35   75000    Finance    Masters   Kisumu           8
49   27   52000  Marketing  Bachelors  Mombasa           3

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=20,test_size=0.2)

In [28]:
print(X_test.shape)
print(X_train.shape)
print("==========")
print(y_test.shape)
print(y_train.shape)

(10, 6)
(40, 6)
==========
(10,)
(40,)

In [ ]:
X_train.head(
    
)